#!/usr/bin/env bun
/**
 * Check which spell effects are not implemented.
 * Attempts to create each effect and reports which throw "Unknown GPEffect type".
 */

import { getEffectManager } from '../src/core/systems/effects/EffectManager';
import { getAllRealms, getRealmSpells } from '../src/core/data/spellLoader';
import type { SpellDef } from '../src/core/data/spells';

const effectManager = getEffectManager();

// Track results
const implemented: Set<string> = new Set();
const stubbed: Map<string, string[]> = new Map(); // effectType -> [realm:spellName]

// Gather all spells from all realms
const allSpells: Array<{ realm: string; spell: SpellDef }> = [];
for (const realm of getAllRealms()) {
  for (const spell of getRealmSpells(realm)) {
    allSpells.push({ realm, spell });
  }
}

for (const { realm, spell } of allSpells) {
  if (!spell.effects) continue;

  for (const effect of spell.effects) {
    try {
      effectManager.createEffect(effect);
      implemented.add(effect.type);
    } catch (e) {
      if (e instanceof Error && e.message.includes('Unknown GPEffect type')) {
        const spells = stubbed.get(effect.type) || [];
        spells.push(`${realm}:${spell.name}`);
        stubbed.set(effect.type, spells);
      } else {
        throw e;
      }
    }
  }
}

// Generate markdown
const lines: string[] = [];
lines.push('# Unimplemented Spell Effects');
lines.push('');
lines.push('*Auto-generated by `bun scripts/check-spell-effects.ts`*');
lines.push('');
const totalStubbedSpells = [...stubbed.values()].reduce((sum, arr) => sum + arr.length, 0);
lines.push(`**${stubbed.size} effect types** are not yet implemented, affecting **${totalStubbedSpells} spells**.`);
lines.push('');
lines.push('| Effect | Spells |');
lines.push('|--------|--------|');

const sortedStubbed = [...stubbed.entries()].sort((a, b) => b[1].length - a[1].length);
for (const [effectType, spells] of sortedStubbed) {
  lines.push(`| \`${effectType}\` | ${spells.join(', ')} |`);
}

const output = lines.join('\n') + '\n';

// Write to file
const outputPath = new URL('../src/data/spells/UNIMPLEMENTED_EFFECTS.md', import.meta.url);
await Bun.write(outputPath, output);
console.log(`Wrote ${outputPath.pathname}`);
